### PR TITLE
Remove lambda parameter from generate code

### PR DESCRIPTION
**Pull request by aliak00**
Is confusing. Also isn't that syntax wrong?

### CODE REVIEW

**Comment by wilzbach** [comment]
See also: https://github.com/dlang-tour/english/pull/200

I think the entire chapter is deeply in need of an overhaul

**Comment by aliak00** [comment]
If it's being changed then i guess go ahead and close this one?

**Comment by wilzbach** [comment]
Sorry that this got stalled for so long in the queue. 

> If it's being changed then i guess go ahead and close this one?

Well that hasn't happened until now -> merging your PR.

**Comment by aliak00** [comment]
No worries 👍 Thanks!

**Pull request merged**
