### PR TITLE
Add a simple language overview

### PR DESCRIPTION
**Pull request by wilzbach**
Reboot of #119 (with working links this time)

### CODE REVIEW

**Comment by wilzbach** [comment]
> Please use internal link format here and not the external. It's an internal link after all and this will force a change of the domain when you're on tour.dlang.io and force a change to HTTPs if you're on HTTP. Additionnaly this prevents local testing after all...

- This was/is blocked by https://github.com/stonemaster/dlang-tour/pull/472, because at the moment the link checking is broken.
- AFAIK we want to force [SSL anyways](https://github.com/stonemaster/dlang-tour/issues/450)
- Links are also checked directly if only one repository is enabled (e.g. with `--lang-dir`), which would lead to an error (with the https://github.com/stonemaster/dlang-tour/pull/472 absolute links shouldn't be checked anymore during development)

**Comment by JackStouffer** [comment]
Can we use the HTTP header `Accept-Language` to redirect people automatically?

**Comment by wilzbach** [comment]
> Can we use the HTTP header Accept-Language to redirect people automatically?

Of course, but most translations aren't finished yet.
I opened an issue at the base repo: https://github.com/stonemaster/dlang-tour/issues/496
(this repo just contains content)

I will merge this now as the previous PR has been approved and this is hasn't received any activity for more than a month.

**Comment by ZombineDev** [comment]
> I will merge this now as the previous PR has been approved and this is hasn't received any activity for more than a month.

Sure, glad to see this finally in!

**Pull request merged**
