### PR TITLE
Add portugese to the listed languages

### PR DESCRIPTION
**Pull request by wilzbach**
@sergiors was Google correct on the translation?

### CODE REVIEW

**Comment by sergiors** [comment]
@wilzbach don't trust in google translate!
I will continue to translate after the brazilian carnival

**Comment by wilzbach** [comment]
@sergiors ah it was just whether Português is the correct translation of Portuguese (for the language index). 

Have fun at the carnival and enjoy your time!!

**Comment by sergiors** [comment]
Yep, it's right, maybe `Brazilian Portuguese - Português Brasileiro` be best, because Europe Portuguese is a little bit different

**Comment by wilzbach** [comment]
> Yep, it's right, maybe Brazilian Portuguese - Português Brasileiro be better,

Thanks a lot!
(changed)

**Pull request merged**
