### PR TITLE
Update templates.md

### PR DESCRIPTION
**Pull request by dataPulverizer**
I have replaced the current templates tour with a highly detailed tutorial on generic and metaprogramming in D.

Thanks

### CODE REVIEW

**Review by pbackus — CHANGES_REQUESTED** [review]
This is a decent first draft of a comprehensive survey of metaprogramming topics in D. Unfortunately, that makes it a poor fit for the D tour, which wants short, focused, introductory articles on individual topics.

If you would like to submit any of this content for inclusion in the D tour, please split it into individual pages, each no more than 200 lines in length and focused on a *single* language feature or programming technique. Some of the material (for example, the part on CTFE) could also be submitted as improvements to existing tour pages.

**Comment by wilzbach** [comment]
Thanks a lot for helping out! I don't have time atm to review in-depth, but a first comment: is there a possibility to split this into two or three sections?
At the moment most sections of the tour are roughly one page, so that the user isn't over-whelmed with content.

**Comment by dataPulverizer** [comment]
Okay. I will rework it and split it into a few sections.

**Comment by dataPulverizer** [comment]
I shall rework this and split it into a few sections.

**Comment by PetarKirov** [comment]
I think the following file structure:

```
tour/
├── metaprogramming
│   ├── 00-intro.md
│   ├── 01-ct-sequences-intro.md
│   ├── 02-ct-sequences-algos.md
│   ├── 03-ctfe.md
│   └── 04-string-mixins.md
└── templates
    ├── 00-intro.md
    ├── 01-function-templates.md
    ├── 02-struct-class-interface-templates.md
    ├── 03-enum-templates.md
    ├── 04-alias-templates.md
    └── 05-mixin-templates.md
```

**Comment by dataPulverizer** [comment]
I'm happy to do this but I created a separate PR https://github.com/dlang-tour/english/pull/342 after cancelling this one. Shall I delete it? I created it because from the above comments, I thought people wanted something smaller and more brief both for each document and for the overall length, and for some reason I didn't think I could submit it in this PR. If so I can rework the material into the structure you have specified. I should probably reopen and work within this PR so the history is retained?

**Pull request closed without merging**
