### PR TITLE
unify comment style - vibed/web-server

### PR DESCRIPTION
**Pull request by wilzbach**
this is just about the style - we might also want to more comments in general here.

### CODE REVIEW

**Comment by ZombineDev** [comment]
I improved some of the comments. Let me know if you agree with the changes.

**Comment by wilzbach** [comment]
> I improved some of the comments. Let me know if you agree with the changes.

Sure. Thanks!

Travis was failing due to the 48 chars line limit, thus I wrapped the first block.
Feel free to merge then ;-)

**Comment by ZombineDev** [comment]
> Travis was failing due to the 48 chars line limit, thus I wrapped the first block.
Feel free to merge then ;-)

Thanks for the fix, at that moment I ran out of time to follow up on the CI.

**Comment by ZombineDev** [comment]
(I didn't merge because I found a couple of typos, but I'll submit a PR in an hour or two.)

**Comment by wilzbach** [comment]
> (I didn't merge because I found a couple of typos, but I'll submit a PR in an hour or two.)

Oh sorry. No worries. Take your time!!

**Pull request merged**
