### PR TITLE
Update basic-types.md

### PR DESCRIPTION
**Pull request by MuriloMir**
Just making it neater, it is neater to have only one line for 8-bit.

### CODE REVIEW

**Comment by Basile-z** [comment]
You have forgot to go back to ~master before making this PR. As a consequence there's the commit of #286 that has slipped in because it's the parent.

**Comment by ZombineDev** [comment]
Rebased on top of master.

**Comment by ZombineDev** [comment]
@Basile-z BTW, I'm using https://github.com/wilzbach/git-tools and with Termux on my Android phone it's just 3 lines:
```
$REPOS/git-tools/pr_checkout dlang-tour/english/pull/285
git rebase master
$REPOS/git-tools/pr_push
```

I also use Fish shell, instead of Bash, so the with the auto-completion it's quite fast to type.

**Comment by ZombineDev** [comment]
@MuriloMir yep, as @Basile-z said make sure that your master branch is up to date before making commits. In general, a good git workflow would be:
* always create a new topic git branch before making changes
* don't make commits directly on your master branch
* sync your master branch before creating a new branch
* sync your master branch and rebase your topic branch on top of master, before pushing

In other words, this look like this when using git from command-line:

```bash
# Check where your git remotes point to.
# By convention, `origin` points to your GitHub fork
# (in this case https://github.com/MuriloMir/english)
# and `upstream` points to the project you're contributing to
# (where you want to open a pull-request with your changes).
git remote -v
# should print:
origin  git@github.com:MuriloMir/english.git (fetch)
origin  git@github.com:MuriloMir/english.git (push)
upstream        git@github.com:dlang-tour/english (fetch)
upstream        git@github.com:dlang-tour/english (push)
# ... if you're using SSH, or correspondingly with HTTPS:
origin  https://github.com/MuriloMir/english.git (fetch)
origin  https://github.com/MuriloMir/english.git (push)
upstream  https://github.com/dlang-tour/english.git (fetch)
upstream  https://github.com/dlang-tour/english.git (push)
# (The benefit of using SSH is that you don't need to retype
# your GitHub username and password everytime you push
# to GitHub and that you can use your single SSH key
# with many git repo hosting services (e.g. GitLab, BitBucket, etc.).)

# Make sure your master branch is up to date:
git checkout master
git pull --ff-only upstream master

# Create a new local branch for your changes and switch to it:
git checkout -b make-basic-types-table-neater

# Make your changes and when you're done with them
# commit them to git:
git commit -m "Make the table in basic-types.md neater"

# Optionally, before pushing your changes to GitHub, if several
# hours, days, months have passed since you last synced your master branch
# you may need to sync it again in order to get new commits that may
# have been merged by others upstream, in the mean time.

git checkout master
git pull --ff-only upstream master

# You may also want to update the master branch on your fork,
# so that you can open pull request directly from GitHub's UIi:
git push -f origin master

# After syncing your master branch, go back to your topic branch
# and rebase it on top of master:
git checkout make-basic-types-table-neater
# (Note: to create a new branch the `-b` flag needs to be passed
# but afterwards, when simply switching between existing branches,
# the `-b` flag should not be specified.)
git rebase master
# After this step you may need to resolve any merge conflicts
# if there were changes to the file(s) that you have been editing
# made by others in the meantime.

# Finally, push your local branch to your fork on GitHub:
git push origin make-basic-types-table-neater

# And open a pull request through GitHub's UI.
```

**Comment by Basile-z** [comment]
Yeah a little "git rebase -i master" after pulling, then mark the unwanted commit as to  "drop" would have worked too.

**Comment by ZombineDev** [comment]
If you have commits on the master branch a normal `git pull` would fail. `git pull --rebase upstream master` should work though.

**Pull request merged**
